# Generated by Django 4.0.3 on 2023-10-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_appointment_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default=False, max_length=100, null=True),
        ),
    ]
