# Generated by Django 4.0.3 on 2023-10-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0009_remove_appointment_date_remove_appointment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('canceled', 'canceled'), ('complete', 'Complete')], default='created', max_length=100, null='created'),
        ),
    ]
